version: "3.3"
services:
  backend:
    build: ./backend
    ports:
      - "9009:8000"
    volumes:
      - ./backend/app:/usr/src/backend/app
    tty: true
    restart: always
    environment:
      - ENV=development
      - PORT=4000
      - MONGO_URL=mongodb://mongo:27017/
      - MONGO_DB=timaptest
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=admin
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    depends_on:
        - mongo
  


